---
# tasks file for update
- import_tasks: update-ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'
  tags:
    - update

- import_tasks: update-centos.yml
  when: ansible_facts['distribution'] == 'CentOS'
  tags:
    - update

- import_tasks: update-windows.yml
  when: ansible_facts['os_family'] == 'Windows'
  tags:
    - update